/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicsElements;

import java.awt.Color;

/**
 *
 * @author jpasqualini
 */
public class WordCloudContainer extends javax.swing.JPanel {

    /**
     * Creates new form WordCloudContainer
     * @param c color of the background
     * @param s string to display within panel
     */
    public WordCloudContainer(Color c, String s) {
        initComponents();
        this.setBackground(c);
        this.nameComponentLabel.setText(s);
//        this.setLayout(null);
//        this.nameComponentLabel.setLayout(null);
//        this.nameComponentLabel.setBounds(this.getVisibleRect());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameComponentLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(250, 60));
        setMinimumSize(new java.awt.Dimension(250, 60));

        nameComponentLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        nameComponentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameComponentLabel.setText("Element");
        nameComponentLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.darkGray));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameComponentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameComponentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameComponentLabel;
    // End of variables declaration//GEN-END:variables
}
